// AUTO-GENERATED by scripts/build-tokens-2.mjs from design-tokens/tokens-old.json
// Do not hand-edit — re-run `npm run build:tokens` instead.

export const colors2 = {
  "white": "#FFFFFF",
  "black": "#000000",
  "gray-50": "#FAFAFA",
  "gray-100": "#F4F4F5",
  "gray-200": "#E4E4E7",
  "gray-300": "#D4D4D8",
  "gray-400": "#A1A1AA",
  "gray-500": "#71717A",
  "gray-600": "#52525B",
  "gray-700": "#3F3F46",
  "gray-800": "#27272A",
  "gray-900": "#18181B",
  "gray-950": "#09090B",
  "primary-10": "#f8fbff",
  "primary-20": "#f5f9ff",
  "primary-30": "#F3F8FF",
  "primary-40": "#d4e5ff",
  "primary-50": "#b5d2ff",
  "primary-60": "#96bfff",
  "primary-70": "#76abff",
  "primary-80": "#5796ff",
  "primary-90": "#3881ff",
  "primary-100": "#196BFF",
  "supporting-70": "#3761AD",
  "supporting-indigo-100": "#312E81",
  "success-10": "#f1f7f0",
  "success-20": "#EBF3E9",
  "success-30": "#d3e6ce",
  "success-40": "#bbdbb2",
  "success-50": "#A2D195",
  "success-60": "#93C385",
  "success-70": "#75b562",
  "success-80": "#5b9e47",
  "success-90": "#477E36",
  "success-100": "#3c6b2e",
  "warning-10": "#f8d17b",
  "warning-20": "#F5BD42",
  "warning-30": "#f2b63d",
  "warning-40": "#eeaf39",
  "warning-50": "#eaa834",
  "warning-60": "#E6A130",
  "warning-70": "#c48929",
  "warning-80": "#a17122",
  "warning-90": "#7f591a",
  "warning-100": "#5c4013",
  "danger-10": "#f1ab99",
  "danger-20": "#ed957d",
  "danger-30": "#e97e61",
  "danger-40": "#E56745",
  "danger-50": "#e03e22",
  "danger-60": "#BF281B",
  "danger-70": "#a22217",
  "danger-80": "#861c13",
  "danger-90": "#69160f",
  "danger-100": "#4c100b",
  "info-10": "#f0f7fd",
  "info-20": "#EAF3FC",
  "info-30": "#bbd7f8",
  "info-40": "#88b8f7",
  "info-50": "#5294f9",
  "info-60": "#196BFF",
  "info-70": "#155bd9",
  "info-80": "#124bb3",
  "info-90": "#0e3b8c",
  "info-100": "#0a2b66",
  "text-heading": "#18181B",
  "text-primary": "#27272A",
  "text-secondary": "#71717A",
  "text-disabled": "#D4D4D8",
  "text-on-primary": "#FFFFFF",
  "text-link": "#196BFF",
  "bg-page": "#FAFAFA",
  "bg-layout": "#F4F4F5",
  "bg-card": "#FFFFFF",
  "bg-nested-card": "#FAFAFA",
  "bg-well": "#F4F4F5",
  "bg-primary-subtle": "#F3F8FF",
  "border-default": "#D4D4D8",
  "border-subtle": "#E4E4E7",
  "border-strong": "#A1A1AA",
  "border-focus": "#196BFF",
  "primary-default": "#196BFF",
  "primary-hover": "#3881ff",
  "primary-pressed": "#5796ff",
  "primary-disabled": "#D4D4D8",
  "danger-default": "#BF281B",
  "danger-hover": "#a22217",
  "success-default": "#477E36",
  "warning-default": "#E6A130",
  "focus-ring": "#196BFF",
  "focus-ring-danger": "#BF281B"
} as const;

export const shadowColors2 = {
  "shadow-xs": "#0A0D120D",
  "shadow-sm": "#0A0D121A",
  "shadow-md": "#0A0D1224",
  "shadow-lg": "#0A0D122E",
  "shadow-xl": "#0A0D1238"
} as const;

export const shadowScale2 = [
  {
    "tier": "xs",
    "token": "shadow-xs",
    "boxShadow": "0 1px 2px 0 #0A0D120D"
  },
  {
    "tier": "sm",
    "token": "shadow-sm",
    "boxShadow": "0 1px 3px 0 #0A0D121A"
  },
  {
    "tier": "md",
    "token": "shadow-md",
    "boxShadow": "0 4px 8px 0 #0A0D1224"
  },
  {
    "tier": "lg",
    "token": "shadow-lg",
    "boxShadow": "0 8px 16px 0 #0A0D122E"
  },
  {
    "tier": "xl",
    "token": "shadow-xl",
    "boxShadow": "0 12px 24px 0 #0A0D1238"
  }
] as const;

export const radius2 = {
  "none": 0,
  "xs": 2,
  "sm": 4,
  "md": 6,
  "lg": 8,
  "xl": 10,
  "2xl": 12,
  "3xl": 16,
  "4xl": 20,
  "5xl": 24,
  "full": 9999
} as const;

export const spacing2 = {
  "none": 0,
  "xxs": 2,
  "xs": 4,
  "sm": 8,
  "md": 12,
  "lg": 16,
  "xl": 24,
  "2xl": 32,
  "3xl": 56,
  "4xl": 64,
  "5xl": 80,
  "6xl": 96,
  "7xl": 128,
  "8xl": 160
} as const;

export const fontFamily2 = "Inter";

export const fontWeights2 = {
  "regular": "Regular",
  "medium": "Medium",
  "semibold": "Semibold",
  "bold": "Bold"
} as const;

export const fontWeightNumbers2 = {
  "regular": 400,
  "medium": 500,
  "semibold": 600,
  "bold": 700
} as const;

export const typeScale2 = [
  {
    "name": "caption",
    "slug": "caption",
    "size": 12
  },
  {
    "name": "body-sm",
    "slug": "body-sm",
    "size": 14
  },
  {
    "name": "body-md",
    "slug": "body-md",
    "size": 16
  },
  {
    "name": "body-lg",
    "slug": "body-lg",
    "size": 18
  },
  {
    "name": "h4",
    "slug": "h4",
    "size": 20
  },
  {
    "name": "h3",
    "slug": "h3",
    "size": 24
  },
  {
    "name": "h2",
    "slug": "h2",
    "size": 30
  },
  {
    "name": "h1",
    "slug": "h1",
    "size": 36
  },
  {
    "name": "display",
    "slug": "display",
    "size": 48
  }
] as const;

export const lineHeights2 = [
  {
    "name": "tight",
    "value": 1.2
  },
  {
    "name": "normal",
    "value": 1.5
  },
  {
    "name": "relaxed",
    "value": 1.75
  }
] as const;

export const componentHeights2 = [
  {
    "name": "xxs",
    "px": 22
  },
  {
    "name": "xs",
    "px": 24
  },
  {
    "name": "sm",
    "px": 26
  },
  {
    "name": "md",
    "px": 28
  },
  {
    "name": "lg",
    "px": 30
  },
  {
    "name": "xl",
    "px": 32
  }
] as const;

export const iconSizes2 = [
  {
    "name": "sm",
    "px": 16
  },
  {
    "name": "md",
    "px": 20
  },
  {
    "name": "lg",
    "px": 24
  }
] as const;
