// AUTO-GENERATED by scripts/build-tokens.mjs from design-tokens/tokens.json
// Do not hand-edit — re-run `npm run build:tokens` instead.

export const colors = {
  "border-1": "#d9d9d940",
  "border-split": "#f0f0f040",
  "bg-container-1": "#ffffff40",
  "bg-layout": "#f5f5f540",
  "bg-group-card": "#f0f0f0",
  "card": "#ffffff",
  "nested-card": "#fafafa",
  "well": "#f0f0f0",
  "secondary-bg": "#f0f8ff",
  "secondary-2-bg": "#f5f5f5",
  "text-heading": "#3b3e45",
  "text-primary": "#2a2c32",
  "text-secondary": "#6c707a",
  "text-disabled": "#878a92",
  "gray-1": "#fafafa",
  "gray-2": "#f4f5f5",
  "gray-3": "#efeff0",
  "gray-4": "#e7e8e9",
  "gray-5": "#d7d8db",
  "gray-6": "#bcbec2",
  "gray-7": "#a1a4aa",
  "gray-8": "#878a92",
  "gray-9": "#6c707a",
  "gray-10": "#53575f",
  "gray-11": "#3b3e45",
  "gray-12": "#2a2c32",
  "gray-13": "#1c1d22",
  "primary-0": "#f3f6ff",
  "primary-1": "#e6eaf6",
  "primary-2": "#c2cdea",
  "primary-3": "#91a6d9",
  "primary-4": "#5e7cc8",
  "primary-5": "#2e54b7",
  "primary-6": "#002fa7",
  "primary-7": "#00288e",
  "primary-8": "#002177",
  "primary-9": "#001b5f",
  "primary-10": "#00154b",
  "error-bg": "#f7f3f3",
  "error-border": "#e7bbbd",
  "error-base": "#c00c15",
  "error-text": "#69070c",
  "warning-bg": "#f7f5f2",
  "warning-border": "#ead6b8",
  "warning-base": "#d17f05",
  "warning-text": "#774903",
  "success-bg": "#f4f6f4",
  "success-border": "#c8dacd",
  "success-base": "#238b3d",
  "success-text": "#10411d",
  "info-bg": "#f3f6f7",
  "info-border": "#badae8",
  "info-base": "#097dae",
  "info-text": "#053e57",
  "focus-ring": "#002fa7",
  "focus-ring-error": "#c00c15"
} as const;

export const shadowColors = {
  "shadow-skeumorphic-inner-border": "#0a0d122e",
  "shadow-skeumorphic-inner": "#0a0d120d",
  "shadow-3xl_02": "#0a0d120a",
  "shadow-2xl_02": "#0a0d120a",
  "shadow-2xl_01": "#0a0d122e",
  "shadow-3xl_01": "#0a0d1224",
  "shadow-md_02": "#0a0d120f",
  "shadow-md_01": "#0a0d121a",
  "shadow-xl_02": "#0a0d1208",
  "shadow-xl_01": "#0a0d1214",
  "shadow-lg_03": "#0a0d120a",
  "shadow-lg_02": "#0a0d1208",
  "shadow-lg_01": "#0a0d1214",
  "shadow-xl_03": "#0a0d120a",
  "shadow-sm_02": "#0a0d121a",
  "shadow-sm_01": "#0a0d121a",
  "shadow-xs": "#0a0d120d"
} as const;

export const shadowScale = [
  {
    "tier": "xs",
    "boxShadow": "0 1px 2px 0px #0a0d120d",
    "layers": [
      {
        "token": "shadow-xs",
        "color": "#0a0d120d",
        "css": "0 1px 2px 0px #0a0d120d"
      }
    ]
  },
  {
    "tier": "sm",
    "boxShadow": "0 1px 2px 0px #0a0d121a, 0 1px 3px 0px #0a0d121a",
    "layers": [
      {
        "token": "shadow-sm_01",
        "color": "#0a0d121a",
        "css": "0 1px 2px 0px #0a0d121a"
      },
      {
        "token": "shadow-sm_02",
        "color": "#0a0d121a",
        "css": "0 1px 3px 0px #0a0d121a"
      }
    ]
  },
  {
    "tier": "md",
    "boxShadow": "0 2px 4px -1px #0a0d121a, 0 4px 6px -1px #0a0d120f",
    "layers": [
      {
        "token": "shadow-md_01",
        "color": "#0a0d121a",
        "css": "0 2px 4px -1px #0a0d121a"
      },
      {
        "token": "shadow-md_02",
        "color": "#0a0d120f",
        "css": "0 4px 6px -1px #0a0d120f"
      }
    ]
  },
  {
    "tier": "lg",
    "boxShadow": "0 2px 4px -2px #0a0d1214, 0 4px 8px -2px #0a0d1208, 0 8px 16px -4px #0a0d120a",
    "layers": [
      {
        "token": "shadow-lg_01",
        "color": "#0a0d1214",
        "css": "0 2px 4px -2px #0a0d1214"
      },
      {
        "token": "shadow-lg_02",
        "color": "#0a0d1208",
        "css": "0 4px 8px -2px #0a0d1208"
      },
      {
        "token": "shadow-lg_03",
        "color": "#0a0d120a",
        "css": "0 8px 16px -4px #0a0d120a"
      }
    ]
  },
  {
    "tier": "xl",
    "boxShadow": "0 4px 8px -2px #0a0d1214, 0 8px 16px -4px #0a0d1208, 0 12px 24px -6px #0a0d120a",
    "layers": [
      {
        "token": "shadow-xl_01",
        "color": "#0a0d1214",
        "css": "0 4px 8px -2px #0a0d1214"
      },
      {
        "token": "shadow-xl_02",
        "color": "#0a0d1208",
        "css": "0 8px 16px -4px #0a0d1208"
      },
      {
        "token": "shadow-xl_03",
        "color": "#0a0d120a",
        "css": "0 12px 24px -6px #0a0d120a"
      }
    ]
  },
  {
    "tier": "2xl",
    "boxShadow": "0 8px 16px -4px #0a0d122e, 0 16px 24px -4px #0a0d120a",
    "layers": [
      {
        "token": "shadow-2xl_01",
        "color": "#0a0d122e",
        "css": "0 8px 16px -4px #0a0d122e"
      },
      {
        "token": "shadow-2xl_02",
        "color": "#0a0d120a",
        "css": "0 16px 24px -4px #0a0d120a"
      }
    ]
  },
  {
    "tier": "3xl",
    "boxShadow": "0 12px 24px -6px #0a0d1224, 0 20px 32px -6px #0a0d120a",
    "layers": [
      {
        "token": "shadow-3xl_01",
        "color": "#0a0d1224",
        "css": "0 12px 24px -6px #0a0d1224"
      },
      {
        "token": "shadow-3xl_02",
        "color": "#0a0d120a",
        "css": "0 20px 32px -6px #0a0d120a"
      }
    ]
  }
] as const;

export const insetShadows = [
  {
    "name": "skeumorphic-inner",
    "token": "shadow-skeumorphic-inner",
    "boxShadow": "inset 0 1px 2px #0a0d120d"
  },
  {
    "name": "skeumorphic-inner-border",
    "token": "shadow-skeumorphic-inner-border",
    "boxShadow": "inset 0 0 0 1px #0a0d122e"
  }
] as const;

export const radius = {
  "3xl": 20,
  "2xl": 16,
  "xl": 12,
  "lg": 10,
  "full": 9999,
  "sm": 6,
  "md": 8,
  "xs": 4,
  "4xl": 24,
  "xxs": 2,
  "none": 0
} as const;

export const spacing = {
  "4xl": 32,
  "2xl": 20,
  "xl": 16,
  "lg": 12,
  "sm": 6,
  "xs": 4,
  "11xl": 160,
  "10xl": 128,
  "9xl": 96,
  "8xl": 80,
  "7xl": 64,
  "3xl": 24,
  "6xl": 48,
  "none": 0,
  "5xl": 40,
  "md": 8,
  "xxs": 2
} as const;

export const fontFamily = "Inter";

export const fontWeights = {
  "bold": "Bold",
  "semibold-italic": "Semibold italic",
  "semibold": "Semibold",
  "medium-italic": "Medium italic",
  "bold-italic": "Bold italic",
  "medium": "Medium",
  "regular-italic": "Regular italic",
  "regular": "Regular"
} as const;

export const fontWeightNumbers = {
  "regular": 400,
  "medium": 500,
  "semibold": 600,
  "bold": 700
} as const;

export const typeScale = [
  {
    "name": "H1",
    "slug": "h1",
    "size": 42,
    "lineHeight": 72,
    "lineHeightToken": "H1 2"
  },
  {
    "name": "H2",
    "slug": "h2",
    "size": 35,
    "lineHeight": 60,
    "lineHeightToken": "H2 2"
  },
  {
    "name": "Body",
    "slug": "body",
    "size": 14,
    "lineHeight": null,
    "lineHeightToken": null
  },
  {
    "name": "H5",
    "slug": "h5",
    "size": 20,
    "lineHeight": 32,
    "lineHeightToken": "H5 2"
  },
  {
    "name": "Title",
    "slug": "title",
    "size": 17,
    "lineHeight": null,
    "lineHeightToken": null
  },
  {
    "name": "H3",
    "slug": "h3",
    "size": 29,
    "lineHeight": 44,
    "lineHeightToken": "H3 2"
  },
  {
    "name": "Caption",
    "slug": "caption",
    "size": 12,
    "lineHeight": 18,
    "lineHeightToken": "caption 2"
  },
  {
    "name": "H4",
    "slug": "h4",
    "size": 24,
    "lineHeight": 38,
    "lineHeightToken": "H4 2"
  },
  {
    "name": "Badge Text",
    "slug": "badge-text",
    "size": 10,
    "lineHeight": null,
    "lineHeightToken": null
  }
] as const;

export const orphanLineHeights = [
  {
    "token": "body-lg 2",
    "value": 28
  },
  {
    "token": "H6 2",
    "value": 30
  },
  {
    "token": "display-md 2",
    "value": 94
  },
  {
    "token": "body-md 2",
    "value": 24
  },
  {
    "token": "display-lg 2",
    "value": 104
  },
  {
    "token": "display-sm 2",
    "value": 84
  },
  {
    "token": "body-sm 2",
    "value": 20
  }
] as const;
